# Generated by Django 5.2.11 on 2026-04-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sumber_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
