# Generated by Django 5.2.11 on 2026-04-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='waktu_proses',
            field=models.FloatField(default=0.0),
        ),
    ]
